
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author TechnoPower
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    
    //Valores del cmbBox
    //Tacos
    String[] tacos = {"Elija los tacos","Tacos alpastor","Tacos de barbacoa","Tacos de alambre","Tacos de carnitas", "Tacos de lengua","Tacos de suadero","Tacos de buche", "Tacos de canasta"};
    double preciosTacos[]={0,15,5,14.50,35,30,20,17,5,2,17,60,200};
    double precioT = 0;
    int cantidadT = 0;
    //Salsa
    String[] salsa = {"Elija las salsa", "Roja", "Verde", "Naranja"};
    double preciosSalsa[]={0,1,1,2};
    double precioS = 0;
    int cantidadS = 0;
    
    //Modifica el modelo de la tabla
    DefaultTableModel modelo= new DefaultTableModel();
    
    //Guardara las ventas con los atributos
    ArrayList<Venta> listaVentas = new ArrayList<Venta>();
    
    public Menu() {
        initComponents();
        
    //Centra el jframe en medio
        this.setLocationRelativeTo(null);
    //Modifica el tamaño del JFrame 
        this.setSize(700, 600);
    
    //Obtiene los valores para el comboBox    
    //Valores para tacos    
    DefaultComboBoxModel aModel = new DefaultComboBoxModel(tacos);
        cmbBxTacos.setModel(aModel);
        cmbBxTacos.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                System.out.println(cmbBxTacos.getSelectedItem());
            }
        });
     //Valores para Salsas
     DefaultComboBoxModel sModel = new DefaultComboBoxModel(salsa);
        cmbBxSalsa.setModel(sModel);
        cmbBxSalsa.addActionListener(new ActionListener(){

            @Override
            public void actionPerformed(ActionEvent e) {
                System.out.println(cmbBxSalsa.getSelectedItem());
            }
        
        });
     
     //Aqui se agrega el icono del jFrame
        this.setTitle("Los tacos hermanos");
        Image icono=Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Imagenes/Logo.jpg"));
        this.setIconImage(icono);
   
     //Nombre de la columnas
        modelo.addColumn("Descripcion");
        modelo.addColumn("Precio");
        modelo.addColumn("Ordenes");
        modelo.addColumn("Importe");
        actualizarTabla();
        
        calcularPrecio();    
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cmbBxSalsa = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        cmbBxVerduras = new javax.swing.JComboBox();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMenu = new javax.swing.JTable();
        spnTacos = new javax.swing.JSpinner();
        spnSalsa = new javax.swing.JSpinner();
        jSpinner3 = new javax.swing.JSpinner();
        jSpinner4 = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblPrecio = new javax.swing.JLabel();
        lblImporte = new javax.swing.JLabel();
        btnAgregarTacos = new javax.swing.JButton();
        lblSubtotal = new javax.swing.JLabel();
        lblIVA = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        cmbBxTacos = new javax.swing.JComboBox();
        cmbBxBebida = new javax.swing.JComboBox();
        btnAgregarVerduras = new javax.swing.JButton();
        btnAgregarSalsa = new javax.swing.JButton();
        btnAgregarBebidas = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Menu");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("SALSAS");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, -1, -1));

        cmbBxSalsa.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbBxSalsa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbBxSalsaActionPerformed(evt);
            }
        });
        getContentPane().add(cmbBxSalsa, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, 210, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("TACOS");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, -1, -1));

        cmbBxVerduras.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbBxVerduras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbBxVerdurasActionPerformed(evt);
            }
        });
        getContentPane().add(cmbBxVerduras, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, 210, -1));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("Usuario");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(544, 10, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("VERDURAS");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("BEBIDAS");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, -1, -1));

        tblMenu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblMenu);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 590, 140));

        spnTacos.setModel(new javax.swing.SpinnerNumberModel(1, 1, 10, 1));
        spnTacos.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spnTacosStateChanged(evt);
            }
        });
        getContentPane().add(spnTacos, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 100, 39, -1));

        spnSalsa.setModel(new javax.swing.SpinnerNumberModel(1, 1, 10, 1));
        spnSalsa.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spnSalsaStateChanged(evt);
            }
        });
        getContentPane().add(spnSalsa, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 140, 39, -1));

        jSpinner3.setModel(new javax.swing.SpinnerNumberModel(1, 1, 10, 1));
        getContentPane().add(jSpinner3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 180, 39, -1));

        jSpinner4.setModel(new javax.swing.SpinnerNumberModel(1, 1, 10, 1));
        getContentPane().add(jSpinner4, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 220, 39, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Precio");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 260, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Importe");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 250, -1, -1));

        lblPrecio.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblPrecio.setText("$0.00MXN");
        getContentPane().add(lblPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 260, -1, 14));

        lblImporte.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblImporte.setText("$0.00MXN");
        getContentPane().add(lblImporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 260, -1, 14));

        btnAgregarTacos.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnAgregarTacos.setText("Agregar");
        btnAgregarTacos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarTacosActionPerformed(evt);
            }
        });
        getContentPane().add(btnAgregarTacos, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 100, 100, -1));

        lblSubtotal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblSubtotal.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblSubtotal.setText("$0.00MXN");
        getContentPane().add(lblSubtotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(342, 442, 110, -1));

        lblIVA.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblIVA.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblIVA.setText("$0.00MXN");
        getContentPane().add(lblIVA, new org.netbeans.lib.awtextra.AbsoluteConstraints(342, 472, 110, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("TOTAL");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, 502, -1, -1));

        lblTotal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblTotal.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTotal.setText("$0.00MXN");
        getContentPane().add(lblTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(342, 502, 110, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setText("IVA");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, 472, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setText("SUBTOTAL");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, 442, -1, -1));

        cmbBxTacos.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbBxTacos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbBxTacosActionPerformed(evt);
            }
        });
        getContentPane().add(cmbBxTacos, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 210, -1));

        cmbBxBebida.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(cmbBxBebida, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, 210, -1));

        btnAgregarVerduras.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnAgregarVerduras.setText("Agregar");
        getContentPane().add(btnAgregarVerduras, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 220, 100, 20));

        btnAgregarSalsa.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnAgregarSalsa.setText("Agregar");
        btnAgregarSalsa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarSalsaActionPerformed(evt);
            }
        });
        getContentPane().add(btnAgregarSalsa, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 140, 100, -1));

        btnAgregarBebidas.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnAgregarBebidas.setText("Agregar");
        getContentPane().add(btnAgregarBebidas, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 180, 100, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Index obj1 = new Index();
        obj1.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        Contraseña obj2 = new Contraseña();

    }//GEN-LAST:event_jButton1MouseClicked

    private void cmbBxVerdurasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbBxVerdurasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbBxVerdurasActionPerformed

    private void btnAgregarTacosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarTacosActionPerformed
        // TACOS
        Venta ventaT = new Venta();
        ventaT.setId(cmbBxTacos.getSelectedIndex());
        ventaT.setDescripcion(cmbBxTacos.getSelectedItem().toString());
        ventaT.setPrecio(precioT);
        ventaT.setCantidad(cantidadT);
        ventaT.setImporte(precioT*cantidadT);
        
        if(!buscarVenta(ventaT)){
            listaVentas.add(ventaT);
        }
        actualizarTabla();
        borrarVenta();
    }//GEN-LAST:event_btnAgregarTacosActionPerformed

    private void cmbBxTacosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbBxTacosActionPerformed
        calcularPrecio();
    }//GEN-LAST:event_cmbBxTacosActionPerformed

    private void spnTacosStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spnTacosStateChanged
        calcularPrecio();
    }//GEN-LAST:event_spnTacosStateChanged

    private void cmbBxSalsaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbBxSalsaActionPerformed
        calcularPrecio();
    }//GEN-LAST:event_cmbBxSalsaActionPerformed

    private void spnSalsaStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spnSalsaStateChanged
        calcularPrecio();
    }//GEN-LAST:event_spnSalsaStateChanged

    private void btnAgregarSalsaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarSalsaActionPerformed
        // SALSAS
        Venta ventaS = new Venta();
        ventaS.setId(cmbBxSalsa.getSelectedIndex());
        ventaS.setDescripcion(cmbBxSalsa.getSelectedItem().toString());
        ventaS.setPrecio(precioS);
        ventaS.setCantidad(cantidadS);
        ventaS.setImporte(precioS*cantidadS);
        if(!buscarVenta(ventaS)){
            listaVentas.add(ventaS);
        }
        if(!buscarVenta(ventaS)){
            listaVentas.add(ventaS);
        }
        actualizarTabla();
        borrarVenta();
    }//GEN-LAST:event_btnAgregarSalsaActionPerformed

    //Agrega la nueva venta a una venta anterior
    public boolean buscarVenta(Venta nueva){
        for (Venta v : listaVentas){
            if(v.getId()==nueva.getId()){
                int nuevaCantidad=v.getCantidad()+nueva.getCantidad();
                v.setCantidad(nuevaCantidad);
                v.setImporte(v.getPrecio()*nuevaCantidad);
                return true;
            }
        }
        return false;
    }
    
    //
    public void borrarVenta(){
        //TACOS
        precioT = 0;
        cantidadT = 1;
        cmbBxTacos.setSelectedIndex(0);
        spnTacos.setValue(1);
        // SALSAS
        precioS = 0;
        cantidadS = 1;
        cmbBxSalsa.setSelectedIndex(0);
        spnSalsa.setValue(1);
        calcularPrecio();
    }
    
    public void calcularPrecio(){
        //Tacos
        precioT = preciosTacos[cmbBxTacos.getSelectedIndex()];
        cantidadT = Integer.parseInt(spnTacos.getValue().toString());
        //Salsa
        precioS = preciosSalsa[cmbBxSalsa.getSelectedIndex()];
        cantidadS = Integer.parseInt(spnSalsa.getValue().toString());
        
        // TACOS
        lblPrecio.setText(aMoneda(precioT));
        lblImporte.setText(aMoneda(precioT*cantidadT));
        //SALSAS
        lblPrecio.setText(aMoneda(precioS));
        lblImporte.setText(aMoneda(precioS*cantidadS));
    }
    
    //Recibe el precio para darle el formato de moneda
    public String aMoneda(double precio){
    //Regresa un String
        return "$" + Math.round(precio*100.0)/100.0 + "MXN";
    }
    
    public void actualizarTabla(){
        while(modelo.getRowCount()>0){
            modelo.removeRow(0);            
        }
        double subtotal=0;
        for (Venta v : listaVentas){
            Object x[]= new Object[5];
            x[0]=v.getDescripcion();
            x[1]=aMoneda(v.getPrecio());
            x[2]=v.getCantidad();
            x[3]=aMoneda(v.getImporte());
            subtotal+=v.getImporte();
            modelo.addRow(x);
        }
        double iva=subtotal*0.16;
        double total=subtotal+iva;
        lblSubtotal.setText(aMoneda(subtotal));
        lblIVA.setText(aMoneda(iva));
        lblTotal.setText(aMoneda(total));
        tblMenu.setModel(modelo);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarBebidas;
    private javax.swing.JButton btnAgregarSalsa;
    private javax.swing.JButton btnAgregarTacos;
    private javax.swing.JButton btnAgregarVerduras;
    private javax.swing.JComboBox cmbBxBebida;
    private javax.swing.JComboBox cmbBxSalsa;
    private javax.swing.JComboBox cmbBxTacos;
    private javax.swing.JComboBox cmbBxVerduras;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinner3;
    private javax.swing.JSpinner jSpinner4;
    private javax.swing.JLabel lblIVA;
    private javax.swing.JLabel lblImporte;
    private javax.swing.JLabel lblPrecio;
    private javax.swing.JLabel lblSubtotal;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JSpinner spnSalsa;
    private javax.swing.JSpinner spnTacos;
    private javax.swing.JTable tblMenu;
    // End of variables declaration//GEN-END:variables
}
